title: "yoon gaemi devlife"
author: "Yoongaemi"
description: "점점 낮아지는 기억력을 보충하기위해 시작하는 블로그"
baseurl: ""  # 사용자 페이지라면 빈 값, 프로젝트라면 "/repo-name"
url: "https://yoongaemi.github.io"

# Minimal Mistakes 테마 적용
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

# Google Analytics (선택)
analytics:
  provider: "google"
  google:
    tracking_id: "UA-XXXXXXXXX-X"

# Markdown 설정
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# SEO 및 소셜 미디어 설정
social:
  name: ""
  links:
    - "https://github.com/yoongaemi"

# 네비게이션 메뉴 설정
nav:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"
  - title: "About"
    url: "/about/"
